### ISSUE TITLE
dist directory

### ISSUE THREAD

**Issue by tylergraf** [localForage/localForage-sessionStorageWrapper#5]
Hi, we're installing with bower still which comes directly from github. Will you commit the `dist` directory as well? This is breaking us.

**Comment by thgreasi** [comment]
Hi, I was actually planning to drop bower support for v1.3.0 but forgot to do so...
Please use `bower install localforage-sessionstoragewrapper@1.2` for now and I will try to cut a v1.3.1 release during the weekend and drop bower support in v1.4.0.

**Comment by thgreasi** [comment]
Oh wait. I did drop bower in v1.3, which is just a rewrite in typescript.
Is there a reason that you really need v1.3 and can't use v1.2?
If so (please explain why) then I can do the aforementioned maneuver.

**Comment by tylergraf** [comment]
No, it's ok. I was just major pinned. I'll minor pin until we get to npm.

**Comment by thgreasi** [comment]
Didn't have in mind that bower would continue to pick new GH tags after dropping the bower.json .
Sorry for the inconvenience.
